1. Створення масивів

Створіть (кожен пункт оцінюється в 0.5 бала):

- Масив зі списку [5, 15, 25, 35, 45]
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи np.arange()

In [2]:
! pip show numpy

Name: numpy
Version: 2.3.5
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: Copyright (c) 2005-2025, NumPy Developers.
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are
 met:

     * Redistributions of source code must retain the above copyright
        notice, this list of conditions and the following disclaimer.

     * Redistributions in binary form must reproduce the above
        copyright notice, this list of conditions and the following
        disclaimer in the documentation and/or other materials provided
        with the distribution.

     * Neither the name of the NumPy Developers nor the names of any
        contributors may be used to endorse or promote products derived
        from this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED

In [3]:
import numpy as np

In [4]:
np

<module 'numpy' from '/opt/anaconda3/envs/data-loves/lib/python3.13/site-packages/numpy/__init__.py'>

In [15]:
# Створення масивів. Масив зі списку [5, 15, 25, 35, 45]

arr = np.array([5, 15, 25, 35, 45])
print(arr)  # [5 15 25 35 45]

[ 5 15 25 35 45]


In [16]:
# Масив з нулів розміром 7

zeros = np.zeros(7)
print(zeros)

[0. 0. 0. 0. 0. 0. 0.]


In [20]:
# Масив з одиниць розміром 6

ones = np.ones(6) 
print(ones)

[1. 1. 1. 1. 1. 1.]


In [19]:
# Масив з числами від 10 до 19 використовуючи np.arange()

range_arr = np.arange(10, 20)
print(range_arr)

[10 11 12 13 14 15 16 17 18 19]


2. Базові операції

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над оригінальним масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):

- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів
- Виведіть результат виконання кожної операції.

In [31]:
arr = np.array([12, 24, 36, 48, 60])
print(arr)

[12 24 36 48 60]


In [32]:
multiplied = arr * 2
print(multiplied)

[ 24  48  72  96 120]


In [33]:
added = arr + 10
print(added)

[22 34 46 58 70]


In [34]:
squared = arr ** 2
print(squared)

[ 144  576 1296 2304 3600]


In [35]:
sqrt_arr = np.sqrt(arr)
print(sqrt_arr)

[3.46410162 4.89897949 6.         6.92820323 7.74596669]


3. Статистичні функції

Створіть Numpy-масив data зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):

- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [44]:
data = np.array([18, 27, 33, 41, 52, 68, 79])

#Середнє значення
display(data.mean()) 

#Мінімум
display(data.min()) 

#Максимум
display(data.max()) 

#Суму всіх елементів
display(data.sum()) 

np.float64(45.42857142857143)

np.int64(18)

np.int64(79)

np.int64(318)

4. Індексація

Створіть Numpy-масив arr зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):

- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [50]:
arr = np.array([15, 22, 35, 44, 58, 67])

# Перший елемент
print(arr[0])
# Останній елемент
print(arr[-1])
# Елементи з індексами 1 до 3
print(arr[1:4])
# Елементи більші за 40
print(arr[arr > 40])

15
67
[22 35 44]
[44 58 67]


5. Двовимірні масиви

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):

- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [64]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

# Виведіть форму (shape) матриці
display(matrix.shape) 
# Виведіть перший рядок
print(matrix[0, :])
# Виведіть другу колонку
print(matrix[:, 1])
# Обчисліть суму всіх елементів
display(matrix.sum()) 
# Обчисліть середнє всіх елементів
display(matrix.mean()) 

(3, 3)

[2 4 6]
[ 4 10 16]


np.int64(90)

np.float64(10.0)