### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [68]:
import numpy as np
import matplotlib.pyplot as plt

In [69]:
vector = np.random.rand(10)

vector

array([0.97231149, 0.31880911, 0.07554458, 0.00227555, 0.30787511,
       0.38971278, 0.19816779, 0.45170217, 0.97653257, 0.07595457])

In [70]:
vector.shape

(10,)

In [71]:
B = np.array([[11, 14, 17],
              [20, 23, 26],
              [29, 32, 35]])

In [72]:
print("Матриця B:")
print(B)

Матриця B:
[[11 14 17]
 [20 23 26]
 [29 32 35]]


In [73]:
B.shape

(3, 3)


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [74]:
# Додайте до кожного значення вектора vector число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
A1 = vector +10
A1

array([10.97231149, 10.31880911, 10.07554458, 10.00227555, 10.30787511,
       10.38971278, 10.19816779, 10.45170217, 10.97653257, 10.07595457])

In [75]:
A2 = np.round(A1, 2)
A2

array([10.97, 10.32, 10.08, 10.  , 10.31, 10.39, 10.2 , 10.45, 10.98,
       10.08])

In [76]:
# Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.

B2 = B * 2
B2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [77]:
# Створіть новий вектор, який містить квадрат кожного vector без циклів.
vector_squared = vector ** 2
vector_squared

array([9.45389627e-01, 1.01639251e-01, 5.70698319e-03, 5.17813626e-06,
       9.47870863e-02, 1.51876049e-01, 3.92704711e-02, 2.04034850e-01,
       9.53615859e-01, 5.76909645e-03])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [78]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

1. Задані дві матриці A і Bрозмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю result_matrix на екран.

In [79]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]]
)

In [80]:
A.shape

(3, 2)

In [81]:
B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]]
)

In [82]:
B.shape

(2, 3)

In [83]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [84]:
result_matrix.shape

(2, 2)

2. Заданий вектор C розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите result_matrix на вектор C і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [85]:
C.shape

(2, 1)

In [86]:
result_matrix.shape

(2, 2)

In [87]:
result_vector = np.dot(result_matrix, C)

result_vector

array([[0.5202],
       [0.2846]])

In [88]:
result_vector.shape

(2, 1)

3. Задана матриця D розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите result_matrix на матрицю D і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [89]:
D.shape

(2, 2)

In [90]:
D

array([[0, 1],
       [1, 0]])

In [91]:
result_vector2 = np.dot(result_matrix, D)

result_vector2

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




1. Транспонуйте result_matrix.

In [92]:
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [93]:
result_matrix_T = result_matrix.T

result_matrix_T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [94]:
result_matrix_T.shape

(2, 2)

2. Зробіть транспонування вектора vector і виведіть форму нової структури. Чи бачите ви зміну?

In [95]:
vector

array([0.97231149, 0.31880911, 0.07554458, 0.00227555, 0.30787511,
       0.38971278, 0.19816779, 0.45170217, 0.97653257, 0.07595457])

In [96]:
vector_T = vector.T

vector_T

array([0.97231149, 0.31880911, 0.07554458, 0.00227555, 0.30787511,
       0.38971278, 0.19816779, 0.45170217, 0.97653257, 0.07595457])

In [102]:
vector.shape, vector_T.shape

((10,), (10,))

Ні, змін немає, бо vector є одновимірним масивом з формою (10,).

3. Використайте операцію numpy.expand_dims над вектором vector з аргументом axis=1. Запишіть отриманий результат в змінну column_vector і виведіть на екран. Порівняйте з vector.

In [97]:
column_vector = np.expand_dims(vector, axis=1)

column_vector

array([[0.97231149],
       [0.31880911],
       [0.07554458],
       [0.00227555],
       [0.30787511],
       [0.38971278],
       [0.19816779],
       [0.45170217],
       [0.97653257],
       [0.07595457]])

In [98]:
vector.shape, column_vector.shape

((10,), (10, 1))

Після використання np.expand_dims(vector, axis=1) вектор став двовимірною структурою з формою (10, 1). На відміну від vector, який має форму (10,), column_vector виглядає як вектор-стовпчик.

4. Зробіть транспонування column_vector, виведіть результат на екран разом з розмірностями отриманої структури.

In [103]:
column_vector_T = column_vector.T

print("Транспонований column_vector:")
print(column_vector_T)

print("Розмірність:")
print(column_vector_T.shape)

Транспонований column_vector:
[[0.97231149 0.31880911 0.07554458 0.00227555 0.30787511 0.38971278
  0.19816779 0.45170217 0.97653257 0.07595457]]
Розмірність:
(1, 10)
